services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    image: jhj0517/advancedliveportrait-webui:latest

    volumes:
      # Update paths to mount models and output paths to your custom paths like this, e.g:
      # - C:/your-local-path/AdvancedLivePortrait-WebUI/models:/AdvancedLivePortrait-WebUI/models
      # - C:/your-local-path/AdvancedLivePortrait-WebUI/outputs:/AdvancedLivePortrait-WebUI/outputs
      - /AdvancedLivePortrait-WebUI/models
      - /AdvancedLivePortrait-WebUI/outputs

    ports:
      - "7860:7860"

    stdin_open: true
    tty: true

    entrypoint: ["python", "app.py", "--server_port", "7860", "--server_name", "0.0.0.0",]

    # If you're not using Nvidia GPU, Update device to match yours.
    # See more info at : https://docs.docker.com/compose/compose-file/deploy/#driver
    # Edit `requirements.txt` to `requirements-cpu.txt` in Dockerfile as well, if you're not using Nvidia GPU.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]